build:
  version: "1.0"

accounts:
  message: "Welcome to Bank card related prod APIs"
  contactDetails:
    name: "White Buffalo - Product Owner"
    email: "contato@whitebuffalo.prod.br"
  onCallSupport:
    - (+55) 061 96352-2222
    - (+55) 061 3003-3322
