build:
  version: "2.0"

cards:
  message: "Welcome to Bank card related QA APIs"
  contactDetails:
    name: "Luca Stricagnoli - Quality Assurance Lead"
    email: "contato@lucastricagnoli.qa.br"
  onCallSupport:
    - (+55) 021 98765-4321
    - (+55) 021 8080-5544
