build:
  version: "2.0"

loans:
  message: "Welcome to Bank loan related QA APIs"
  contactDetails:
    name: "Tim Berners-Lee - Quality Assurance Lead"
    email: "contato@timbernerslee.qa.br"
  onCallSupport:
    - (+55) 021 98765-4321
    - (+55) 021 9090-5544
